service: ppotto-after-burner
frameworkVersion: "3"
# 플러그인 구성
plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
# 람다 구성
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: "*"
        - Effect: Allow
          Action:
            - vpc:DescribeSecurityGroups
            - ec2:DescribeSubnets
            - ec2:DescribeVpcs
          Resource: "*"
# 핸들러 구성
functions:
  imageProcess:
    handler: src/file-process/image-process-handler.imageProcess
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-0a70e433226a8ae5f
      subnetIds:
        - subnet-027da75b887da566b
    events:
      - s3:
          bucket: ppotto-resource-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
          existing: true
      - s3:
          bucket: ppotto-resource-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
          existing: true
